### ISSUE TITLE
-s and -t options do not respect absolute paths

### ISSUE THREAD

**Issue by aajonusonline** [nwg-piotr/nwg-bar#1]
-t and -s options assume `~/.config/<file_name>`, and do not respect absolute path like `~/custom_config_path/<file_name>`.
https://github.com/nwg-piotr/nwg-bar/blob/306b632f71a1a74e24ef1f8c381c7c203716089c/main.go#L106
This interprets my argument as `~/.config/custom_config_path/<file_name>`
A simple check for the leading `/` would suffice for now, if the `templateFileName` starts with `/`, instead of joining it with `configDir`, it should just use it by itself. Same thing for css file.
https://github.com/nwg-piotr/nwg-bar/blob/306b632f71a1a74e24ef1f8c381c7c203716089c/main.go#L117

Also notice that one code snippet uses `configDir()` and other uses `configDirectory`, this should also be fixed.

Same thing should also be done for https://github.com/nwg-piotr/nwg-drawer

**Comment by nwg-piotr** [comment]
> do not respect absolute path

Well, this is intentional and works the same way in all the nwg-shell components. IMO it should not be changed in one of them only, if at all.

**Comment by aajonusonline** [comment]
> Well, this is intentional and works the same way in all the nwg-shell components. IMO it should not be changed in one of them only, if at all.

Why is it intentional at all? What problem does it solve? I don't see it being useful at all. And i agree, it should be changed in all of the components, and it is trivial to do so.

**Comment by nwg-piotr** [comment]
My advice: try being more polite while submitting issues / PRs.

**Comment by aajonusonline** [comment]
> My advice: try being more polite while submitting issues / PRs.

Not to bug you with criticism, i think it's a great program! I just think this specific behavior is not standard and weird, and can be fixed in 5 minutes. Wouldn't you agree?

**Comment by nwg-piotr** [comment]
> I just think this specific behavior is not standard and weird, and can be fixed in 5 minutes. 

I don't like to write long paths, so chosen to do it this way. Of course this may be changed easily. I just think the contributor needs to justify changes, not the author - their original code.

**Comment by aajonusonline** [comment]
So are you not going to merge then?

**Comment by nwg-piotr** [comment]
Why? I'll merge as soon as I'm back home.
