### ISSUE TITLE
Cosmetic Consideration For Dual Headed Nerds

### ISSUE THREAD

**Issue by thesunexpress** [nwg-piotr/nwg-bar#10]
Current setup is a FreeBSD box, running OpenBox, with a NVidia Quadro P1000 GPU with 2x 27-inch LCD panels attached.
This is a First World Problem, I know. 

Is there any way to have both panels dim when running nwg-bar? 
Currently what happens, is when nwg-bar runs, only the most recently selected desktop will dim & display the buttons lock/exit/reboot/shutdown; whilst the other display remains displaying as if nwg-bar is *not* running --- no dimming etc.

Any pointers on how to achieve, if at all possible, this cosmetic adjustment?
There doesn't appear to be anything obvious in the config files / manual on how to achieve this. There is absolutely nothing amiss with nwg-bar itself, of course, it runs & executes as intended & this 'issue' would only affect the few super-nerds who insist that more than 1 monitor is absolutely required.

**Comment by nwg-piotr** [comment]
I'm not sure what dimming you mean. Could you show me the command you run nwg-bar with, and your `bar.json` content?

**Comment by thesunexpress** [comment]
Situation is as follows:
- Launch `nwgbar`
- Display goes translucent black & buttons for Lock / Logout / Reboot / Shutdown appears
- On a dual-head setup (1 GPU, 2 displays attached) only 1 display goes translucent black & displays the 4 buttons. The second display remains unchanged.

My bar.json is completely untouched. It is exactly how the file is created automatically when `nwgbar` is run for the first time.
It would be nice, again just a purely cosmetic issue as `nwgbar` runs & functions as intended, if both displays (or all displays in the case of 2 / 3 / 4 multi-head display setups on 1 GPU) switch to at least the same translucent black screen & one of the displays shows the 4 buttons for Lock / Logout / Reboot / Shutdown.

**Comment by nwg-piotr** [comment]
OK, gotcha. You use the `nwgbar` command, which is a part of [nwg-launchers](https://github.com/nwg-piotr/nwg-launchers), but submitted the issue to another repository. [I no longer support that project](https://github.com/nwg-piotr/nwg-launchers#this-project-is-community-driven). You need to ask for help up there. The main developer is @Siborgium.
