### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by eddsalkield** [nwg-piotr/nwg-bar#13]
I'm looking to use the fast selection feature [here](https://github.com/nwg-piotr/nwg-bar/issues/9), but it seems that it's still in branch `accel` and not `main`. Also it seems that there's a commit in that branch to bump the version number to 0.1.1, but the commit wasn't tagged nor is it in `main`.

Would you wiling to merge the accel commit into main and release the new version?

**Comment by nwg-piotr** [comment]
It seems you're right. This app is so simple that I've almost forgotten about it.

**Comment by nwg-piotr** [comment]
Done.

**Comment by eddsalkield** [comment]
Thanks!
