### ISSUE TITLE
Invalid CSS prints file not found

### ISSUE THREAD

**Issue by asbachb** [nwg-piotr/nwg-bar#17]
When you try to load a CSS which has an invalid syntax it's classified as "file not found" when you try to run nwg-bar with that css.

```
[asbachb@arch-t14s nwg-bar]$ nwg-bar -t ~/.config/nwg-bar/bar-reboot.json -s /home/asbachb/.config/nwg-bar/style-reboot.css 
2 items loaded from template /home/asbachb/.config/nwg-bar/bar-reboot.json
Preferring dark theme variants
/home/asbachb/.config/nwg-bar/style-reboot.css file not found, using GTK styling
```

**Comment by nwg-piotr** [comment]
Yeah, I'll change it to `fmt.Printf("%s file erroneous or not found, using GTK styling\n", *cssFileName)` in line 144. https://github.com/nwg-piotr/nwg-bar/blob/194bfce1c24165009e800985474db1e50b0af23c/main.go#L144

**Comment by nwg-piotr** [comment]
Just check if the file exists. If it does, it must be buggy. 😄
