### ISSUE TITLE
Question/Feature: Multilayer bars

### ISSUE THREAD

**Issue by asbachb** [nwg-piotr/nwg-bar#18]
I try to implement a sub bar "Reboot to...". So the idea would be to open a new bar to be able to boot into Windows or to Bios.

```json
  {
    "label": "Reboot to...",
    "exec": "/usr/bin/nwg-bar nwg-bar -t /home/asbachb/.config/nwg-bar/bar-reboot.json -s /home/asbachb/.config/nwg-bar/style-reboot.css",
    "icon": "/usr/share/nwg-bar/images/system-reboot.svg"
  },
```

I tried it this way, but the new bar is not showing up.

**Comment by nwg-piotr** [comment]
Just one instance of nwg-bar is allowed at a time. See: https://github.com/nwg-piotr/nwg-bar/blob/194bfce1c24165009e800985474db1e50b0af23c/main.go#L78
