### ISSUE TITLE
CSS transform doesn't work?

### ISSUE THREAD

**Issue by RannyBergamotte** [nwg-piotr/nwg-bar#22]
I was styling the menu, and wanted to make it so when I hover, the icon grows slightly bigger. I tried using `transform: scale(1.2)`, but that didn't work, and said that there was an error in CSS file and it fell back to GTK theme. Out of curiosity I also tried `transform: rotate(20deg);`, and that also caused it to fail.

**Comment by nwg-piotr** [comment]
I haven't ever tried this property. You may want to take a look at this: https://docs.gtk.org/gtk3/css-properties.html

**Comment by RannyBergamotte** [comment]
Ah ok, didn't know it was rendering css through gtk, although now that makes sooooo much more sense (not only with this but everything else using gtk). I was reading the CSS docs for web development on W3 schools.

Thanks a lot, I will close this issue for now then, and read the gtk docs and find a solution tommorow. 

Love the nwg-bar too, feels great, fits in nicely with my system themes after customization, and super simple!

**Comment by husseljoo** [comment]
@RannyBergamotte so how did you do it?
