### ISSUE TITLE
Sleep button

### ISSUE THREAD

**Issue by alexschneider** [nwg-piotr/nwg-bar#24]
Based on #6 I added this to my config:

```
  {
    "label": "Sleep",
    "exec": "systemctl hybrid-sleep",
    "icon": "/usr/share/nwg-bar/images/sleep-light.svg"
  },
```

It'd be good if this were a default configuration option I think, but either way I wanted to create this issue as documentation in case anyone else is also interested in how to do this. 

[More documentation on systemd sleep options](https://man.archlinux.org/man/systemd-sleep.8#DESCRIPTION). I think `hybrid-sleep` makes the most sense but `suspend` might be slightly less at risk for adverse effects as it's just suspend to RAM.

**Comment by nwg-piotr** [comment]
LOL, my intention was to make an app to create button bars for every occasion, not an oblogout replacement. :rofl: The template it comes from is just an example.

**Comment by alexschneider** [comment]
Ah sorry, my bad. I had some trouble figuring out where to change this configuration when running nwg-shell, and thought this was the primary repo for the config that lives in `~/.config/nwg-bar/bar.json`. Is there a better repo for issues related to that configuration?

**Comment by nwg-piotr** [comment]
> Ah sorry, my bad.

Not really: it's a common mistake. Thanks for adding this content. All in all everyone uses nwg-bar this way. :)
