### ISSUE TITLE
Reducing keystroke distance

### ISSUE THREAD

**Issue by Esgeriath** [nwg-piotr/nwg-bar#26]
When having more items in nwg-bar, it takes many keystrokes to get to the last ones using arrow keys. When many items are used frequently, simply changing order of of them does not solve the problem.

This could be improved by adding cyclic motion and/or setting default item focused at the start (one of the middle ones, or one selected by user in config file). Either option can half the maximum distance needed to travel.

**Comment by nwg-piotr** [comment]
nwg-bar supports the gtk.button `use-underline` property. Just use `"label": "_Logout",` instead of "Logout" in your template to access the button with `Alt+l`. Repeat for other buttons.

**Comment by akdevservices** [comment]
> nwg-bar supports the gtk.button `use-underline` property. Just use `"label": "_Logout",` instead of "Logout" in your template to access the button with `Alt+l`. Repeat for other buttons.

Could you add this to README, please.

**Comment by nwg-piotr** [comment]
> Could you add this to README, please.

Sure. Done.
