### ISSUE TITLE
Add a way to disable icons

### ISSUE THREAD

**Issue by J4C0B3Y** [nwg-piotr/nwg-bar#28]
Hi, 

Here are some ideas of how this could be implemented:
- An argument for the command
- Setting icon to "disabled" or similar
- Disabling if icon not specified in config

The above will allow the label to be centered as there is no way to hide the icons with gtk css
I'm using font awesome to display icons and then changing the font size in the style.css

![image](https://github.com/nwg-piotr/nwg-bar/assets/69947689/43b72199-ee45-4a35-8466-27126a3ea665)

Thanks!

**Comment by nwg-piotr** [comment]
Why not? I'll take a look at this, maybe this weekend.

**Comment by nwg-piotr** [comment]
This should do the job:

![image](https://github.com/nwg-piotr/nwg-bar/assets/20579136/0b23831f-4bff-4021-b827-0915898280ac)
