### ISSUE TITLE
[Request] Allow referencing user in bar.json

### ISSUE THREAD

**Issue by Mrfiregem** [nwg-piotr/nwg-bar#3]
To allow a kind of universal "logout", I tried setting this in `bar.json`:

```json
{
  "label": "Logout",
  "exec": "loginctl terminate-user $USER",
  "icon": "/usr/share/nwg-bar/images/system-log-out.svg"
}
```

but as expected environment variables aren't parsed. I also tried moving that code into a script and calling the executable using `"exec"`, but that didn't work either when using Sway.

This isn't really a request to add environment variable parsing, but I believe being able to reference the current user would be helpful for this situation and others, potentially.

**Comment by nwg-piotr** [comment]
> I also tried moving that code into a script and calling the executable using "exec", but that didn't work either when using Sway.

This works well for me:

**bar.json:**

```json
[
  {
    "label": "Lock",
    "exec": "swaylock -f -c 000000",
    "icon": "/usr/share/nwg-bar/images/system-lock-screen.svg"
  },
  {
    "label": "Logout",
    "exec": "tu.sh",
    "icon": "/usr/share/nwg-bar/images/system-log-out.svg"
  },
  {
    "label": "Reboot",
    "exec": "systemctl reboot",
    "icon": "/usr/share/nwg-bar/images/system-reboot.svg"
  },
  {
    "label": "Shutdown",
    "exec": "systemctl -i poweroff",
    "icon": "/usr/share/nwg-bar/images/system-shutdown.svg"
  }
]
```

**tu.sh:**

```bash
#!/usr/bin/env bash

loginctl terminate-user $USER

```

**Comment by Mrfiregem** [comment]
Yes, that's what I did in the initial post and it works when calling `nwg-bar` from the terminal, but when calling it using

```sh
bindsym $mod+Escape exec nwg-bar                 # in sway
riverctl map normal $mod Escape spawn 'nwg-bar'  # in river
```

it doesn't work, which was something I should've made more clear earlier. I'm not too sure on if there's a way to pass variables to the program when called this way, so forgive me if it's already possible.

**Comment by izmyname** [comment]
I'd like to request to reopen this issue, as I think - parsing `$USER ` is an important feature. [wlogout](https://github.com/ArtsyMacaw/wlogout), which is also based on GTK and uses JSON format, does this but, it seems, the project is abandoned and it has its own cons.
