### ISSUE TITLE
What does -f option actually do?

### ISSUE THREAD

**Issue by moranbw** [nwg-piotr/nwg-bar#33]
I am a bit confused by what the `-f` option for "take Full screen width/height" actually does?

I noticed an issue here, saying that you did not want to support full screen: https://github.com/nwg-piotr/nwg-bar/issues/30

I want to have "fullscreen" so I can have a dimmed background for the entire screen around the bar when logging out / shutting down / etc.  The `-f` option does not appear to do that, so not sure what it actually is doing (if anything).

The only way I have figured out to do this was a hacky workaround with margin.  It doesn't seem like you are allowed to use values of `100%` in the CSS anywhere like `window`, `outer-box`, or `inner-box`.

```
window {
        background-color: rgba (0, 0, 0, 0.2)
}

/* Inner bar container, surrounds buttons */
#inner-box {
	margin: 4000px;
}
```

If this behavior is out of scope -- understood.  Was just confused by the `-f` option and that old issue.

And thanks for your great projects and contributions to the community!

EDIT for clarity: just running with the default CSS and `-f`options seems to have the same appearance as without. Perhaps this is not the case on **sway**, as I am using **labwc**...

**Comment by nwg-piotr** [comment]
If I remember well, it only works when some position is given:

`nwg-bar -f -p bottom | top | left | right`

**Comment by moranbw** [comment]
Thanks for the response -- I do see the affect with those other positions. But not quite behavior I am looking for. Will play around with it a little -- thanks!
