### ISSUE TITLE
RFE: expand documentation on suspend and lock

### ISSUE THREAD

**Issue by zabbal** [nwg-piotr/nwg-bar#38]
Is there a way to implement usual suspend-and-lock routine with nwg-bar?
If we simply put "systemctl suspend" than after suspend the desktop will be unlocked which is contrary to what people are used to in X11 where desktop is locked after unsuspending.

**Comment by nwg-piotr** [comment]
Although the default config contains power bar-like commands, nwg-bar is nothing but a set of GTK buttons with a command attached to each one. You can use any script you want there.
