### ISSUE TITLE
Source tarball ships with bundled binary

### ISSUE THREAD

**Issue by eddsalkield** [nwg-piotr/nwg-bar#5]
Firstly, thanks so much for your work on this project!
I'm working on a package for alpine, and noticed that v0.0.1 contains a pre-compiled binary in the source files, which obviously isn't compatible with all architectures.  Could we remove this for the next version?

**Comment by nwg-piotr** [comment]
You're right. This was a temporary solution. I planned to change it with the next release, but this certain project has not had any new release so far. :) I'll prepare a new version as soon as I have a spare hour.

**Comment by nwg-piotr** [comment]
Resolved in #8 (by the way).
