### ISSUE TITLE
Sleep button (or sleep icon request)

### ISSUE THREAD

**Issue by eddsalkield** [nwg-piotr/nwg-bar#6]
I'd really like to add a "sleep" button to my instance of `nwg-bar`.  Would you let me know where the icons are derived from so that I could add one that fits with the theme of the rest of the icons?

Additionally, would you consider the integration of a sleep button into the default bar?

**Comment by eddsalkield** [comment]
Thanks! This is ideal :)

**Comment by nwg-piotr** [comment]
Could you tell me what command you use for the sleep button?

**Comment by eddsalkield** [comment]
Sure - that'd be `pm-suspend` from the [`pm-utils`](https://pm-utils.freedesktop.org/wiki/) project - they're distro-agnostic power management scripts :)

**Comment by nwg-piotr** [comment]
Thanks!
