### ISSUE TITLE
Text shadow styling

### ISSUE THREAD

**Issue by eddsalkield** [nwg-piotr/nwg-bar#7]
I think this is probably related to the css styling, but by default the text seems to have a [weird white shadow](https://salkield.uk/images/bar.png) for me.  I checked the css and didn't find an immediately likely culprit.  Any ideas as to what would likely cause it?

**Comment by nwg-piotr** [comment]
You must be using a light theme, and the css is adjusted to dark ones. The current development version allows to make the nwg-bar window use another theme with the `-g` flag. You may either build from the `main` branch, or wait for the nearest release.

**Comment by nwg-piotr** [comment]
Resolved in #8
